stages:
- name: build
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: |-
        mkdir -p /go/src
        ln -s `pwd` /go/src/lingwei
        cd /go/src/lingwei
        CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o lingwei main.go
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tibbersyu/lingwei:v1.0
      pushRemote: true
      registry: index.docker.io
      callbackScript: /callbackscript/java.sh
      callbackScriptParams: CA
      deploy: true
      targetNamespace: default
      workloadId: deployment:default:bafdsa
      port: "8081"
      containerIndex: 1
      deployService: true
    env:
      PLUGIN_DEBUG: "true"
timeout: 60
notification: {}
